// <auto-generated />
using System;
using ChustaSoft.Tools.ExecutionControl.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChustaSoft.Tools.ExecutionControl.Migrations
{
    [DbContext(typeof(ExecutionControlContext))]
    partial class ExecutionControlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.Execution<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<Guid>("ProcessDefinitionId");

                    b.Property<int?>("Result");

                    b.Property<string>("Server");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("Executions","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionEvent<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ExecutionId");

                    b.Property<int>("Status");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("ExecutionEvents","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionModule<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<Guid>("ExecutionId");

                    b.Property<Guid>("ModuleDefinitionId");

                    b.Property<int?>("Result");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("ModuleDefinitionId");

                    b.ToTable("ExecutionModules","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionModuleEvent<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ExecutionModuleId");

                    b.Property<int>("Status");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionModuleId");

                    b.ToTable("ExecutionModuleEvents","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ProcessDefinition<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("ProcessDefinitions","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ProcessModuleDefinition<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("Concurrent");

                    b.Property<Guid>("ProcessDefinitionId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessModuleDefinitions","Management");
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.Execution<System.Guid>", b =>
                {
                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.ProcessDefinition<System.Guid>", "ProcessDefinition")
                        .WithMany("Executions")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionEvent<System.Guid>", b =>
                {
                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.Execution<System.Guid>", "Execution")
                        .WithMany("ExecutionEvents")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionModule<System.Guid>", b =>
                {
                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.Execution<System.Guid>", "Execution")
                        .WithMany("ExecutionModules")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.ProcessModuleDefinition<System.Guid>", "ModuleDefinition")
                        .WithMany("ExecutionModules")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ExecutionModuleEvent<System.Guid>", b =>
                {
                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.ExecutionModule<System.Guid>", "ExecutionModule")
                        .WithMany("ExecutionModuleEvents")
                        .HasForeignKey("ExecutionModuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChustaSoft.Tools.ExecutionControl.Model.ProcessModuleDefinition<System.Guid>", b =>
                {
                    b.HasOne("ChustaSoft.Tools.ExecutionControl.Model.ProcessDefinition<System.Guid>", "ProcessDefinition")
                        .WithMany("ModuleDefinitions")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
